---
- name: ensure destination for compose file exists
  file:
    path: "{{ docker_compose_path }}"
    state: directory

- name: Copy docker-compose file
  copy:
    content: "{{ docker_compose_yaml }}"
    dest: "{{ docker_compose_file }}"
    owner: "{{ docker_compose_owner }}"
    group: "{{ docker_compose_group }}"
    mode: "{{ docker_compose_mode }}"
  when: docker_compose_yaml != "CHANGEME"
  register: config_update